### ISSUE TITLE
questions while trying infer

### ISSUE THREAD

**Issue by JayFu** [YeFeng1993/GhostNet-Keras#1]
Hi YeFeng,

Thanks for your work.

I was trying to download the repo and infer it but I met a error while I do
```
python infer.py -c config/ghost_config.json
```
and it throw 
```
Traceback (most recent call last):
  File "infer.py", line 61, in <module>
    infer()
  File "infer.py", line 48, in infer
    model.load_weights(modelpath)
  File "/media/e/hujiang/anaconda3/envs/tf/lib/python3.6/site-packages/keras/engine/network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "/media/e/hujiang/anaconda3/envs/tf/lib/python3.6/site-packages/keras/engine/saving.py", line 1030, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 0 layers into a model with 175 layers.
```

Seems that the weight file cannot work?

**Comment by YeFeng1993** [comment]
do not use weight file from weight directory

**Comment by JayFu** [comment]
which means that the file `./weight/GhostNet_model.h5` in repo is unusable? Is there any avalible model or weights?

**Comment by YeFeng1993** [comment]
It is unusable，i forget deleting it; You need to train one.
